# Generated by Django 2.2.6 on 2019-10-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsauceapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='details',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
